
[profile.bench]
debug = true

[profile.release]
lto = "fat"

[workspace]
members = [
    "memflow-kvm-ioctl",
    "memflow-kvm"
]

default-members = [
    "memflow-kvm-ioctl",
    "memflow-kvm"
]

[patch.crates-io]
memflow = { path = "../memflow/memflow" }
