name: Build the kernel module

on: [push, pull_request]

jobs:

  build-kmod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install dkms
      - run: source dkms.conf && echo "::set-env name=BUILT_MODULE_NAME::$BUILT_MODULE_NAME" && echo "::set-env name=PACKAGE_VERSION::$PACKAGE_VERSION"
      - run: echo "::set-env name=DKMS_DIR::/usr/src/${BUILT_MODULE_NAME}-${PACKAGE_VERSION}"
      - run: sudo mkdir $DKMS_DIR
      - run: sudo cp -r * $DKMS_DIR
      - run: sudo dkms build -m $BUILT_MODULE_NAME -v $PACKAGE_VERSION
      - run: sudo dkms mktarball -m $BUILT_MODULE_NAME -v $PACKAGE_VERSION --source-only
      - run: sudo dkms mkdeb -m $BUILT_MODULE_NAME -v $PACKAGE_VERSION --source-only
