name: Build the kernel module

on: [push, pull_request]

jobs:

  build:
    runs-on: fedora-latest
    steps:
      - uses: actions/checkout@v2
      - run: source dkms.conf
      - run: export DKMS_DIR=/usr/src/${BUILT_MODULE_NAME}-${PACKAGE_VERSION}
      - run: mkdir $DKMS_DIR
      - run: cp -r * $DKMS_DIR
      - run: dkms build -m $BUILT_MODULE_NAME -v $PACKAGE_VERSION
      - run: dkms mkrpm -m $BUILT_MODULE_NAME -v $PACKAGE_VERSION --source-only
